masterVolume = 1.0
blockBasedSound = true

[chat]
volume = 0.2
pitch = 2.0
pitchRange = 0.1

[chat.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.note_block.hat"

[chatMention]
volume = 0.5
pitch = 1.2
pitchRange = 0.1

[chatMention.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.note_block.bell"

[hotbarScroll]
volume = 0.1
pitch = 2.0
pitchRange = 0.2

[hotbarScroll.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.note_block.hat"

[inventoryOpen]
volume = 0.2
pitch = 1.5
pitchRange = 0.1

[inventoryOpen.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "ui.toast.in"

[inventoryClose]
volume = 0.2
pitch = 1.5
pitchRange = 0.1

[inventoryClose.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "ui.toast.out"

[listScroll]
volume = 0.1
pitch = 1.0
pitchRange = 0.3

[listScroll.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.note_block.hat"

[itemDrop]
volume = 0.1
pitch = 1.5
pitchRange = 0.1

[itemDrop.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.dispenser.launch"

[itemPickup]
volume = 0.2
pitch = 1.5
pitchRange = 0.5

[itemPickup.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.glass.step"

[itemPickupAll]
volume = 0.02
pitch = 2.0
pitchRange = 0.1

[itemPickupAll.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "entity.item.pickup"

[itemClone]
volume = 0.02
pitch = 2.0
pitchRange = 0.1

[itemClone.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "entity.item.pickup"

[itemDelete]
volume = 0.75
pitch = 1.5
pitchRange = 0.0

[itemDelete.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.composter.fill"

[itemDrag]
volume = 0.1
pitch = 2.0
pitchRange = 0.0

[itemDrag.sound.field_14533]
field_13353 = "minecraft"
field_13355 = "block.glass.place"
